/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JmaquinaCategoria.java
 *
 * Created on 30-dic-2011, 0:44:39
 */
package GUI;

import Repositorio.Evento;
import Dominio.ListaCategoria;
import Dominio.ListaEvento;
import Dominio.ListaParticipante;
import Repositorio.Participante;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Eleany G
 */
public class JmaquinaCategoria extends javax.swing.JFrame {
private ListaCategoria comboBoxCategoria= new ListaCategoria();
private Evento eve = new Evento();
private Participante llenarList = new Participante();
private int catIdGlobal;
private int eveIdGlobal;
private int eveNroGan;
        
    
    /** Creates new form JmaquinaCategoria */
    public JmaquinaCategoria() {
        initComponents();
        comboBoxCategoria.categoriaCB(jComboBoxCate);
        apostar.setVisible(false);
        jLabelEve.setVisible(false);
        jComboBoxEvento.setVisible(false);
        jLabelNroG.setVisible(false);
        jLabelNroP.setVisible(false);
        jTextFieldNroG.setVisible(false);
        jTextFieldNroP.setVisible(false);
        jTextFieldTP.setVisible(false);
        jLabelTP.setVisible(false);
        
        
    }
    
    


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jComboBoxCate = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxEvento = new javax.swing.JComboBox();
        jLabelEve = new javax.swing.JLabel();
        jLabelTP = new javax.swing.JLabel();
        jLabelNroP = new javax.swing.JLabel();
        jLabelNroG = new javax.swing.JLabel();
        jTextFieldTP = new javax.swing.JTextField();
        jTextFieldNroP = new javax.swing.JTextField();
        jTextFieldNroG = new javax.swing.JTextField();
        apostar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1090, 720));
        setResizable(false);

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(1090, 720));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(1090, 720));

        jComboBoxCate.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
        jComboBoxCate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        jComboBoxCate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCateItemStateChanged(evt);
            }
        });
        jComboBoxCate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCateActionPerformed(evt);
            }
        });
        jComboBoxCate.setBounds(50, 120, 280, 70);
        jLayeredPane1.add(jComboBoxCate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 48));
        jLabel2.setForeground(new java.awt.Color(227, 224, 0));
        jLabel2.setText("Categorias");
        jLabel2.setBounds(60, 30, 270, 67);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBoxEvento.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
        jComboBoxEvento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione" }));
        jComboBoxEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEventoActionPerformed(evt);
            }
        });
        jComboBoxEvento.setBounds(490, 120, 280, 70);
        jLayeredPane1.add(jComboBoxEvento, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabelEve.setFont(new java.awt.Font("Comic Sans MS", 1, 48));
        jLabelEve.setForeground(new java.awt.Color(227, 224, 0));
        jLabelEve.setText("Eventos");
        jLabelEve.setBounds(530, 30, 220, 70);
        jLayeredPane1.add(jLabelEve, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabelTP.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
        jLabelTP.setForeground(new java.awt.Color(227, 224, 0));
        jLabelTP.setText("Tipo de Pago");
        jLabelTP.setBounds(690, 260, 190, 60);
        jLayeredPane1.add(jLabelTP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabelNroP.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
        jLabelNroP.setForeground(new java.awt.Color(227, 224, 0));
        jLabelNroP.setText("Nro de Participantes");
        jLabelNroP.setBounds(600, 330, 250, 60);
        jLayeredPane1.add(jLabelNroP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabelNroG.setFont(new java.awt.Font("Comic Sans MS", 1, 24));
        jLabelNroG.setForeground(new java.awt.Color(227, 224, 0));
        jLabelNroG.setText("Nro de Ganadores");
        jLabelNroG.setBounds(630, 400, 240, 60);
        jLayeredPane1.add(jLabelNroG, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldTP.setEditable(false);
        jTextFieldTP.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
        jTextFieldTP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 224, 0), 3));
        jTextFieldTP.setBounds(870, 270, 180, 40);
        jLayeredPane1.add(jTextFieldTP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldNroP.setEditable(false);
        jTextFieldNroP.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
        jTextFieldNroP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 224, 0), 3));
        jTextFieldNroP.setBounds(870, 340, 180, 40);
        jLayeredPane1.add(jTextFieldNroP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFieldNroG.setEditable(false);
        jTextFieldNroG.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
        jTextFieldNroG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(227, 224, 0), 3));
        jTextFieldNroG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNroGActionPerformed(evt);
            }
        });
        jTextFieldNroG.setBounds(870, 410, 180, 40);
        jLayeredPane1.add(jTextFieldNroG, javax.swing.JLayeredPane.DEFAULT_LAYER);

        apostar.setFont(new java.awt.Font("Comic Sans MS", 1, 48));
        apostar.setForeground(new java.awt.Color(175, 11, 11));
        apostar.setText("Apostar");
        apostar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        apostar.setBorderPainted(false);
        apostar.setContentAreaFilled(false);
        apostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apostarActionPerformed(evt);
            }
        });
        apostar.setBounds(70, 280, 250, 100);
        jLayeredPane1.add(apostar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/home.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1090, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(1090, 720));
        jLabel1.setPreferredSize(new java.awt.Dimension(1090, 720));
        jLabel1.setBounds(-6, -16, 1100, 830);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1090, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void apostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apostarActionPerformed
   
 //if que valida si deseas apostar con tabla de resultado o no   
  if (eveNroGan>1){
 
int respuesta= JOptionPane.showConfirmDialog(null,"Tabla de Resultado","Desea Apostar con tabla de Resultado",JOptionPane.YES_NO_CANCEL_OPTION,JOptionPane.INFORMATION_MESSAGE);
    
if (respuesta==1){
    new JmaquinaParticipantes(eveIdGlobal).setVisible(true);
                   this.dispose();
}
else{
    if(respuesta==2){
    apostar.setVisible(true);
    }
    else {
        new JmaquinaTablaResultados(eveNroGan,eveIdGlobal).setVisible(true);
        this.dispose();
    } 
   }
  }
  else {
       new JmaquinaParticipantes(eveIdGlobal).setVisible(true);
                   this.dispose();
  }
    
    
    // TODO add your handling code here:
}//GEN-LAST:event_apostarActionPerformed

private void jComboBoxCateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCateItemStateChanged

     apostar.setVisible(false);
        jLabelNroG.setVisible(false);
        jLabelNroP.setVisible(false);
        jTextFieldNroG.setVisible(false);
        jTextFieldNroP.setVisible(false);
        jTextFieldTP.setVisible(false);
        jLabelTP.setVisible(false);
        jLabelEve.setVisible(true);
        jComboBoxEvento.setVisible(true);
     
        
        
    //Guardo lo q seleccione en el combo de categorias
    String catNombre = (String) jComboBoxCate.getSelectedItem();
    //Guardo en variables la informacion de la categoria seleccionada
    int catPosicion = ListaCategoria.buscarCategoriaporNombre(catNombre);
    catIdGlobal = ListaCategoria.lasCategorias.get(catPosicion).getCatId();
    try {
        //lleno la lista de los eventos segun la categoria q selecciones
            eve.consultarPorCat(catIdGlobal,jComboBoxEvento);
   
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(JmaquinaCategoria.class.getName()).log(Level.SEVERE, null, ex);
        }
    // TODO add your handling code here:
}//GEN-LAST:event_jComboBoxCateItemStateChanged

private void jTextFieldNroGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNroGActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextFieldNroGActionPerformed

private void jComboBoxEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEventoActionPerformed
 apostar.setVisible(true);
        jLabelEve.setVisible(true);
        jComboBoxEvento.setVisible(true);
        jLabelNroG.setVisible(true);
        jLabelNroP.setVisible(true);
        jTextFieldNroG.setVisible(true);
        jTextFieldNroP.setVisible(true);
        jTextFieldTP.setVisible(true);
        jLabelTP.setVisible(true);
        
        //Limpio la lista de participantes del evento
         ListaParticipante.losParticipantes.clear();


//Guardo la opcion seleccionana en el combobox en la variable evento
    String eveNombre = (String) jComboBoxEvento.getSelectedItem();
    
 // Guardo en variables la informacion del evento que voy a mostrar en pantalla  
int evePosicion = ListaEvento.buscarEventoNombre(eveNombre);
int eveTipoPago= ListaEvento.losEventos.get(evePosicion).getEveTipoPago();
 eveNroGan = ListaEvento.losEventos.get(evePosicion).getEveNroGan();
int eveNroPart= ListaEvento.losEventos.get(evePosicion).getEveNroPart();
eveIdGlobal= ListaEvento.losEventos.get(evePosicion).getEveId();

//Imprimo en pantalla
String eveNroG= String.valueOf(eveNroGan);
String eveNroP= String.valueOf(eveNroPart);
String eveTipoP= String.valueOf(eveTipoPago);
jTextFieldTP.setText(eveTipoP);
jTextFieldNroP.setText(eveNroP);
jTextFieldNroG.setText(eveNroG);

        try {
            //lleno la lista de participantes de ese evento seleccionado
            llenarList.consultar(eveIdGlobal);

                // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(JmaquinaApuesta.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    // TODO add your handling code here:
}//GEN-LAST:event_jComboBoxEventoActionPerformed

private void jComboBoxCateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCateActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jComboBoxCateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JmaquinaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JmaquinaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JmaquinaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JmaquinaCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JmaquinaCategoria().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apostar;
    private javax.swing.JComboBox jComboBoxCate;
    private javax.swing.JComboBox jComboBoxEvento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEve;
    private javax.swing.JLabel jLabelNroG;
    private javax.swing.JLabel jLabelNroP;
    private javax.swing.JLabel jLabelTP;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTextFieldNroG;
    private javax.swing.JTextField jTextFieldNroP;
    private javax.swing.JTextField jTextFieldTP;
    // End of variables declaration//GEN-END:variables
}
